### PR TITLE
Make the time display more easily parsable by humans

### LINKED ISSUE #15: Humanize the time display
It would be nice if instead of "1837 seconds", the display said "30:37".

### PR DESCRIPTION
**Pull request by skorokithakis**
Since the notification is only shown after 10 seconds, I think the milliseconds display is not very useful. Instead, since this will only be shown for long-running commands, I have changed the format to look like `01:54:22`.

This fixes #15.

### CODE REVIEW

**Comment by aristidesfl** [comment]
On macOS 10.11.6, no time is displayed. This is printed in the console.

```
$ sleep 11
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

**Comment by skorokithakis** [comment]
Hmm, I'm afraid I don't have an OS X machine. Can you debug the date command? I'm using `date -d "1970-01-01 30 seconds" +%H:%M:%S`, which works fine on Linux.

**Comment by aristidesfl** [comment]
Have a look at maybe you can spot the difference https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/date.1.html

**Comment by skorokithakis** [comment]
Looks like you may need `date -d "1970-01-01 30 seconds" "+%H:%M:%S"`, although then that won't work on Linux... Bah.

**Comment by aristidesfl** [comment]
That still doesn’t work on mac though.

**Comment by skorokithakis** [comment]
Sorry, I meant `date -d "1970-01-01 30 seconds" -f "+%H:%M:%S"`

**Comment by aristidesfl** [comment]
Still the same

**Comment by skorokithakis** [comment]
Alright, I think this is done. It should work on all OSes, and the humanization is great. I'm just not sure whether it currently pulls the dependency in correctly, but I think so.

**Comment by aristidesfl** [comment]
Works well, thanks!

A few things before merging: 

1. Squash the commits into one
1. Don't use period in the commit title
1. Should we also remove the period from the notification title?

**Comment by skorokithakis** [comment]
You can squash and edit the merge commit message when merging the PR, Github shows a dialog. About the period in the title, I can remove it if you want.

**Comment by aristidesfl** [comment]
Merged, thanks! 

PS: In the future follow the just now added CONTRIBUTING.md

**Comment by skorokithakis** [comment]
Will do, thanks!

**Pull request merged**
