### PR TITLE
Check active window in Linux

### PR DESCRIPTION
**Pull request by asymmetric**
* Uses xprop to check that the active window is not a terminal
* Uses an array of terminals (currently tmux, iTerm)

Depends on: #7. Closes: #8.

### CODE REVIEW

**Comment by asymmetric** [comment]
@aristidesfl it is, you can get it via [homebrew](https://github.com/Homebrew/homebrew-core/blob/9aa94c6c0bea3cef2d24c412225d2722b9e6ab5b/Formula/tmux.rb) for example.

On the other hand, iTerm definitely isn't a Linux application, but I decided to keep things simple and only use one string to match against, instead of platform-specific ones, as there are no negative consequences in doing so IMO.

But to answer your question, no, I didn't test this on macOS.

**Comment by aristidesfl** [comment]
tmux is a command line application. not macOS application. does the linux terminal you are using get renamed to tmux in xprops when you are using it, instead of its original name?

**Comment by aristidesfl** [comment]
@asymmetric is this terminal detection working on linux for you?

**Comment by asymmetric** [comment]
@aristidesfl yes, it is. I tested termite and Gnome Terminal on i3, and they both set the window name to a string containing "tmux", so they both work.

**Comment by asymmetric** [comment]
So obviously this only works when people are using tmux, which leaves plenty of space for improvement. But the OSX detection of iTerm functions along the same set of assumptions, so I thought it was fine.

**Comment by aristidesfl** [comment]
so is it not possible to get the terminal  application name with xprops on linux?

**Comment by asymmetric** [comment]
I don't get the question. I *am* using `xprop` to get the window name. What am I missing? :confused:

**Comment by asymmetric** [comment]
Ooh, I get it now, sorry! I'll try playing around with `xprop` and see if I can get the *application* name :+1:

**Comment by asymmetric** [comment]
Tested on `termite` and `gnome-terminal`.

**Comment by aristidesfl** [comment]
Cool. The window name could actually be useful. if you can set the window name form the terminal, then would could see if you are in the right window or not, even if you are still using the terminal.

Did you test the applescript with the array?

**Comment by asymmetric** [comment]
Nope, I don't have a macOS machine, sorry.

**Comment by x4121** [comment]
I guess there is still some errors
```
set active_application ...
if echo $active_window ...
```

This doesn't really make sense

**Comment by jbucaran** [comment]
@asymmetric Ping pong.

**Comment by aristidesfl** [comment]
@asymmetric why did you switch from detecting windows to detecting applications?

**Comment by aristidesfl** [comment]
Since there are questions about the code and no answers for a while, I'm closing this.
The functionality has been implemented in https://github.com/fisherman/done/releases/tag/0.5.0
Thank you for the contribution.

**Pull request closed without merging**
